name: Test single folder only

on:
  push:
    branches: [main]
    paths:
        - '/tests/**'
  pull_request:
    branches: [main]
    paths:
        - '/tests/**'

jobs:
  run_tests:
    runs-on: ubuntu
    defaults:
        run:
            working-directory: './tests/'
    steps:
        - name: Checkout repository code
          uses: actions/checkout@v4

        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            node-version: '24'
        
        - name: Install dependencies
          run: npm ci

        - name: Execute folder specific tests
          run: npm test


